# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Introduction To R
author: olendorf
github_username:  olendorf

description: A tutorial to get new users exposed to the essentials of R.
baseurl: "/introduction_to_r" # the subpath of your site, e.g. /blog
url: "https://psu-data-workshops.github.io" # the base hostname & protocol for your site, e.g. http://example.com
lang: en

directory_title: "Workshop Directory"
directory_url: "https://github.com/psu-data-workshops/start_here" # the url to a directory of workshops

production_url : https://github.com/psu-data-workshops/introduction_to_r

BASE_PATH : /introduction_to_r
ASSET_PATH : /introduction_to_r/assets

# This allows us to put supporting files in a different repositry if desired.
supporting_files_url: "https://github.com/psu-data-workshops/introduction_to_r"
supporting_files_path: "/tree/master/supporting_files"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .gitignore

# Build settings
markdown: kramdown# Markdown settings

kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6



theme: jekyll-whiteglass

plugins:
  - jekyll-archives
  - jekyll-sitemap
  
excerpt_separator: "<!-- more -->"
  
collections:
  units:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

